[project]
name = "game"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.asset]
path = "contracts/asset.clar"
depends_on = []
